@local = http://localhost:3000
@render = https://cse341-project2-2x89.onrender.com

### ===== LOCAL =====

### Get all players
GET {{local}}/players

### Get player by id (Messi)
   GET {{local}}/players/6ab5cdfdf6897a7d5d1d3707

### Player not found (valid format, doesn't exist)
GET {{local}}/players/6ab5cdfdf6897a7d5d1d3799

### Invalid id format
GET {{local}}/players/123

### Create player
POST {{local}}/players
Content-Type: application/json

{
  "firstName": "Lautaro",
  "lastName": "Martínez",
  "position": "Forward",
  "jerseyNumber": 22,
  "birthDate": "1997-08-22",
  "birthPlace": "Bahía Blanca, Buenos Aires",
  "currentClub": "Inter Milan",
  "internationalCaps": 70,
  "internationalGoals": 35,
  "worldCupWinner": true
}

### ===== RENDER =====

### Get all players
GET {{render}}/players

### Get player by id (Messi)
GET {{render}}/players/6ab5cdfdf6897a7d5d1d3708

### Update player (Di María - current club example)
PUT {{local}}/players/6ab5cdfdf6897a7d5d1d3707
Content-Type: application/json

{
  "firstName": "Ángel",
  "lastName": "Di María",
  "position": "Winger",
  "jerseyNumber": 11,
  "birthDate": "1988-02-14",
  "birthPlace": "Rosario, Santa Fe",
  "currentClub": "Rosario Central",
  "internationalCaps": 145,
  "internationalGoals": 31,
  "worldCupWinner": true
}

### Delete player (replace with the id of Lautaro after creating him)
DELETE {{local}}/players/6ab5d30914065ebb87538d68